modLoader="javafml"
loaderVersion="${loader_version_range}"
license="GNU LESSER GENERAL PUBLIC LICENSE VERSION 3"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="ParCool+ / Compatibility Addon"
description='''
An addon for ParCool, which support compatibility of animation with some mods
'''

[[mixins]]
config="parcool_compat_addon.mixins.json"

[[dependencies.${mod_id}]]
modId="neoforge"
type="required"
versionRange="${neo_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="minecraft"
type="required"
versionRange="[1.21.1,1.22)"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="parcool"
type="required"
versionRange="[${parcool_version},)"
ordering="BEFORE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="sable"
type="optional"
versionRange="[${sable_version},3)"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="bettercombat"
type="optional"
versionRange="[2.3.2+1.21.1,)"
ordering="BEFORE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="carryon"
type="optional"
versionRange="[2.2.4,)"
ordering="BEFORE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="playeranimator"
type="optional"
versionRange="[2.0.4+1.21.1,)"
ordering="BEFORE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="entity_texture_features"
type="optional"
versionRange="[7.0.13,)"
ordering="BEFORE"
side="CLIENT"

[[dependencies.${mod_id}]]
modId="entity_model_features"
type="optional"
versionRange="[3.0.17,)"
ordering="BEFORE"
side="CLIENT"
