modLoader="javafml"
loaderVersion="${loader_version_range}"
license="GNU LESSER GENERAL PUBLIC LICENSE VERSION 3"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="ParCool+ / Compatibility Addon"
description='''
An addon for ParCool, which support compatibility of animation with some mods
'''

[[dependencies.${mod_id}]]
modId="neoforge"
type="required"
versionRange="${neo_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="minecraft"
type="required"
versionRange="[1.21.1,1.22)"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="parcool"
type="required"
versionRange="[3.4.3.1,)"
ordering="BEFORE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="bettercombat"
type="optional"
versionRange="[2.3.2+1.21.1,)"
ordering="BEFORE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="carryon"
type="optional"
versionRange="[2.2.4,)"
ordering="BEFORE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="playeranimator"
type="optional"
versionRange="[2.0.4+1.21.1,)"
ordering="BEFORE"
side="BOTH"

